#!/bin/bash
# Upload Background Image Script
# This script helps you upload the ASSET.jpg image to the server

echo "=================================================="
echo "  Background Image Upload for Landing Page"
echo "=================================================="
echo ""
echo "To upload the image from your Windows machine:"
echo ""
echo "Option 1: Using SCP (from Windows PowerShell or Command Prompt)"
echo "--------------------------------------------------------------"
echo "scp \"C:\\Users\\jyaruel\\Downloads\\ASSET.jpg\" root@207.246.126.171:/root/assetManagement/src/static/images/"
echo ""
echo "Option 2: Using VS Code"
echo "--------------------------------------------------------------"
echo "1. Open VS Code"
echo "2. Connect to the server"
echo "3. Navigate to: /root/assetManagement/src/static/images/"
echo "4. Right-click and select 'Upload' or drag and drop ASSET.jpg"
echo ""
echo "Option 3: Using WinSCP or FileZilla"
echo "--------------------------------------------------------------"
echo "1. Connect to: 207.246.126.171"
echo "2. Navigate to: /root/assetManagement/src/static/images/"
echo "3. Upload ASSET.jpg from: C:\\Users\\jyaruel\\Downloads\\"
echo ""
echo "After uploading, the background will automatically appear on the landing page!"
echo ""
echo "Current status:"
echo "- Target path: /root/assetManagement/src/static/images/ASSET.jpg"
echo "- Landing page updated: YES ✓"
echo "- Background CSS added: YES ✓"
echo "- Upload pending: YES (waiting for your file)"
echo ""
echo "=================================================="
